### ISSUE TITLE
Unable to boot up test app

### ISSUE THREAD

**Issue by Anbranin** [umts/prawn-rails-forms#39]
```
 can't find executable rackup for gem rack. rack is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
 ```
 So yeah, I know how to fix that, but when I do add rack as a gem I get:
 ```
 .rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/actionpack-6.1.4.1/lib/action_controller/railtie.rb:3:in `require': cannot load such file -- rails (LoadError)
 ```
 Come on man

**Comment by Anbranin** [comment]
Fixed it in my own installation by just doing `gem 'rails', rails_version` in the test_app.rb instead of only installing action_pack and actionview.

**Comment by werebus** [comment]
This is due to `prawn-rails` [slimming down their dependencies](https://github.com/cortiz/prawn-rails/commit/9469566609ff7a5af2f5b6572cd4ea20bd94226b).

It used to depend on `railties` which depends on `actionpack` which depends on `rack`. Now it only depends on `actionview`.

Note that you don't need rack in the testapp itself, you need it in the development dependencies.
